name: "Lakshminarayanan"
tagline: "Building bridges between high-performance computing and artificial intelligence."
email: "ilakshminarayananravi@gmail.com"
location: "Boston, MA"
github: "https://github.com/lakshminarayanannn"
linkedin: "https://linkedin.com/in/r-lakshminarayanan"
badge: "OFFICE OF LAKSHMI"
